---
# tasks file for add-node
- name: Copy Join Command to Nodes
  copy:
    src: "/tmp/join-command.sh"
    dest: "/tmp/join-command.sh"
    mode: ugo=rwx
  tags: cluster-init

- name: Join Node to Cluster
  command: sh /tmp/join-command.sh