---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Create a partition
      parted:
        device: /dev/sdb
        number: 1
        part_end: "100%"
        state: present
    - name: Format new partition
      filesystem:
        fstype: ext4
        dev: /dev/sdb1
    - name: Create mount directory
      file:
        path: /data
        state: directory
    - name: Mount partition
      mount:
        path: /data
        src: /dev/sdb1
        fstype: ext4
        state: mounted

        
##Mount from a nas
---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Create mount directory
      file:
        path: /mnt/share
        state: directory
    - name: Mount NAS
      mount:
        src: 192.168.1.100:/nfs/ssd/shared_data
        path: /mnt/share
        opts: rw,sync,hard
        state: mounted
        fstype: nfs








