apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchExpressions:
      - key: kuberntes.io/metadat.name
        operator: In
        values:
          - mediaserver
          - monitoring
          - default
  serviceMonitorSelector:
    matchLabels:
      serviceType: mediaserver
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: emby
  namespace: mediaserver
  labels:
    serviceType: mediaserver
spec:
  selector:
    matchLabels:
      app: emby
  endpoints:
  - port: "8096"
