---
# tasks file for kubeconfig
- name: mkdir for kubeconfig
  file: 
    path: "/home/{{ kube_user }}/.kube"
    state: directory
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"

- name: Create default kubeconfig for on-master user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kube_config_path }}"
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
    when: default_config

- name: Create new user kubeconfig on external machine
  command: kubectl config set-credentials cluster-admin --client-certificate="{{ certificate_path }}" --client-key="{{ key_path }}" --embed-certs=true
  when: new_user_config
