#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

groups:
  - docker

users:
  - name: tanchwa
    lock_password: true
    shell: /bin/bash
    ssh_authorized_keys:
    - ${init_ssh_public_key}
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL

packages:
  - curl
  - ca-certificates
  - lsb-release
  - gnupg-agent
  - software-properties-common
  - unattended-upgrades

runcmd:
  - export PATH=$PATH:/usr/bin
  - apt update -y
  - apt install -y nginx
  - systemctl start nginx && systemctl enable nginx
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker && systemctl enable docker
  - curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker pull tanchwa/mtg_card_organizer:latest
  - docker run -p8080:8080 tacnhwa/mtg_card_organizer