---
##presetup
#ansible all -i inventory -m command -a 'sudo apt -y install python-simplejson'

#- hosts: webservers
 # become: yes
  #roles:
   # - apache2
    #- common
 # tags:
  #  web

#- hosts: proxy
 # become: yes
  #roles: 
   # - proxy
    #- common
  #tags: proxy

#- hosts: databases
 # become: yes
  #roles:
   # - mariadb
    #- common
  #tags: database

 


- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello world!"
  roles:
    - apache2



  #roles:
  #  - apache2
