name: Docker Image CI

on:
  push:
    paths:
      - '**/MTG_Card_Organizer/**'
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./MTG_Card_Organizer
      run: docker build . --file Dockerfile --tag tanchwa/mtg_card_organizer:latest
    - name: Push the Docker image
      run: docker login -u tanchwa -p ${{ secrets.DOCKER_TOKEN }} && docker push tanchwa/mtg_card_organizer:latest
